### ISSUE TITLE
Contrato da API

### ISSUE THREAD

**Issue by eduardomoroni** [Aprendfy/feed-api#17]
@Aprendfy/dev-team , estava dando uma olhada hoje na API do Aprendfy e gostaria de levantar alguns assuntos para discussão:

**1.  API retornando metadata**
Tdo endpoint retorna  `__V: 0` na resposta, isso vai ser usado para alguma coisa no app? Se não, porque não tirar?
Planejamos usar o `updated_at` e `created_at` no app? Se não porque não tirar também? Quanto menos dado, mais rápido a informação traféga na interwebs :D

**2. API retornando `_id`**
Eu to ligado que o mongo usa isso, mas se a gente expor isso na api nos força a usar _id do lado do app (o que eu não acho legal). E se for mapear `_id` para `id` porque não fazer do lado da API ?

**3. GETs retornando `{ payload: {...}}`**
Esse payload só dificulta o acesso ao resultado, teria algum ganho em seguir esse padrão?
Ao invés de retornar 
```
{
	"payload": [
		{
			"_id": "59634bcf6cd42600116ce458",
			"updated_at": "2017-07-10T09:41:35.574Z",
			"created_at": "2017-07-10T09:41:35.574Z",
			"name": "Facebook",
			"__v": 0
		},
		{
			"_id": "59634c216cd42600116ce459",
			"updated_at": "2017-07-10T09:42:57.453Z",
			"created_at": "2017-07-10T09:42:57.453Z",
			"name": "Google+",
			"__v": 0
		}
	]
}
```
 não seria mais agradavel ter
```
{
	"categories": [
		{
			"id": "59634bcf6cd42600116ce458",
			"name": "Facebook"
		},
		{
			"id": "59634c216cd42600116ce459",
			"name": "Google+"
		}
	]
}
```

**4. Usar `path param` ao invés de `query param`**
Todos nossos endpoints recebem parametros por path com exceção de `/v1/app/posts/?category=${category}` o que acham de mudar o contrato para algo do tipo `/v1/app/${category}/posts`? 
OBS.: Se decidirmos mudar isso seria sensato mudar também como inserimos um post, atualmenta estamos passando uma field `category` no payload da requisição, poderiamos ter um http POST para o mesmo endpoint e remover o field category da requisição.

**5. Todas as requisições são authenticadas**
Como faremos para o app chamar a API? somente usuários logados poderam usar o app? teremos uma conta hardcoded no app e todos usuários usaram a mesma conta para fazer as requisições?

**6. Bearer Token**
O token tem validade? Se sim, como saber se o token expirou para que possamos dar um refresh nele

**8. BONUS Question**
O app atualmente usa cores baseado na categoria, iremos adicionar informação de UI no backend? Iremos hardcodear as cores de acordo com o nome da category?

**Comment by hebertporto** [comment]
**1** - Acho que pode remover, se não me engano eu e o @rafaelsmag já haviamos conversado sobre começar a fazer isso. 

**2** - Não sei o custo de fazer isso, se dá para fazer de forma global ou teria que tratar caso a caso. 

**3** - Esse padrão de resposta na requisição é interessante manter, pois o padrão correto de retorno é assim: 
```
{
        **"message" : "aqui vai uma mensagem quando necessário"**
	"payload": [
		{
			"_id": "59634bcf6cd42600116ce458",
			"updated_at": "2017-07-10T09:41:35.574Z",
			"created_at": "2017-07-10T09:41:35.574Z",
			"name": "Facebook",
			"__v": 0
		},
		{
			"_id": "59634c216cd42600116ce459",
			"updated_at": "2017-07-10T09:42:57.453Z",
			"created_at": "2017-07-10T09:42:57.453Z",
			"name": "Google+",
			"__v": 0
		}
	]
}
```

dentro da resposta vai uma mensagem junto quando dá um erro ou algo do tipo.
Isso padroniza as respostas, ou seja você tem que ficar decorando o que cada endpoint vai trazer como no exemplo que vc citou: o resposta vir dentro de "categories" e aí se for post retorna dentro de "posts' e por aí vai, eu acho mais ok ter um padrão de onde extrair o retorno do dados. 

**5**  No momento as rotas que requerem autenticação são as de Create, Update e Delete, as rotas de login, registro, get post e categorias não precisam. 

dento do src/app.js você vai achar o 'unless'  lá estão as rotas que não precisam de authenticação.

**Comment by eduardomoroni** [comment]
@hebertporto 
3 - Mas de qualquer jeito você não precisa decorar o que tem dentro do payload?
`https://aprendfy.herokuapp.com/v1/app/categories/`
```
{
	"payload": [
		{
			"_id": "59634bcf6cd42600116ce458",
			"updated_at": "2017-07-10T09:41:35.574Z",
			"created_at": "2017-07-10T09:41:35.574Z",
			"name": "Facebook",
			"__v": 0
		},
		{
			"_id": "59634c216cd42600116ce459",
			"updated_at": "2017-07-10T09:42:57.453Z",
			"created_at": "2017-07-10T09:42:57.453Z",
			"name": "Google+",
			"__v": 0
		}
	]
}
```
`https://aprendfy.herokuapp.com/v1/app/posts/`
```
{
	"payload": {
		"__v": 0,
		"updated_at": "2017-07-10T09:54:20.438Z",
		"created_at": "2017-07-10T09:54:20.438Z",
		"title": "Criar uma Página no Facebook",
		"category": "Facebook",
		"readingTime": "4 minutos",
		"level": "Iniciante",
		"body": "Ainda assim, existem dúvidas a respeito de como a",
		"image": "http://i.huffpost.com/gen/3971736/images/o-HAPPY-PEOPLE-facebook.jpg",
		"ownerId": "596349c46cd42600116ce457",
		"_id": "59634ecc6cd42600116ce460"
	}
}
```

tendo ou não o field `payload` você ainda precisa saber o que ta vindo na resposta (dentro ou fora do `payload`, nestes dois casos se eu não soubesse como é representado o `post` ou o `category` eu não conseguiria acessar.
A diferença é como acessamos o valor `payload[0].name`/`categories[0].name`, `payload.title`/`post.title`
A segunda alternativa parece mais entendivel, se eu vejo um categories em algum lugar eu tenho certeza que eu posso acessa-lo como uma category, mas se eu vejo um payload num faço ideia do que é a menos que eu abra [ou log] o objeto

**Comment by eduardomoroni** [comment]
@hebertporto 
2 - Não precisaria mudar a implementação do mongo, só na hora de retornar o objeto para a API mudar o `_id` para `id`

**Comment by hebertporto** [comment]
@eduardomoroni sobre as rotas é assim no app vc recuperar o   categorias: response.payload 
se for posts vai ser posts: response.payload 

Você sabe que se vc está pedindo uma lista de posts/categories vc tem um array, se é busca por um item vc tem um objeto. é um padrão de retorno, agora se tirar o payload a gente tem

cateogories: response.categories e o mesmo com post, e aí pode começar a vir uma variação de retorno 
.. response.categoriesList / reponse.categoriesArray  
é mais fácil controlar o retorno se vc sabe que é tiver que vir de reposta da api sempre vem dentro do payload.

**Comment by eduardomoroni** [comment]
Mas a resposta da API deveria vir dentro da response. Mas é só uma idéia.

Não entendi o response.categoriesList e o response.categoriesArray. responda de API não deve conter detalhes de implementação.

**Comment by hebertporto** [comment]
![image](https://user-images.githubusercontent.com/619062/28023635-cd79c7d4-6564-11e7-957e-fa01bf753d7c.png)

Veja o response é o retorno da requisição. 
dentro do response sempre vem algo além da resposta de dados puro
um response geralmente é assim:
```
{
 status: 200,
 payload: {..} ou um [],
...
}
```
e aí fica padronizado, ter um variável pra indicar onde é que vem os dados da API, data, payalod, uo repetir o response, enfim. 

O que eu entendi é que você quer é mudar o payload para um nome mais expressivo, mas para mim isso não faz muito sentido pq teria que ficar pegando qual é o nome do campo de resposta. 

Sobre o tipo de retorno, é um padrão receber um objeto ou um array de objetos.

**Comment by eduardomoroni** [comment]
Beleza vamos manter então, meus 2 cents sobre isso.
1. Ter status como response.
A resposta já tem um status, porque duplicar a informação.

2. Field message
Porque ter um field message para sucesso se o status deveria ser coerente, se eu preciso de uma message para explicar um retorno com sucesso algo está complicado. 200 é 200, 201 é 201, etc...
Outro ponto é ter um campo opcional numa resposta o ideal seria sempre ter esse campo mesmo que retorne em branco. Em JS isso passa despercebido porque `const { message } = response; // message is undefined` nem sempre chega a quebrar o app, já que fazer algo do tipo `if (message)` não quebraria o app, Porém outras linguagens quebrariam o APP tendo esse tipo de comportamento, porque message seria mapeado para null ou algo do tipo que traria problemas. 

3. Código legivel
Olhando esse código é facil perder o foco do que está acontecendo, função `verifyResponse` o que é verificar a resposta? Todas as respostas, independente de qual seja tem a mesma verificação?
`const { payload } = response;` isto é tão generico que não tem como eu olhando o código entender o que é esse payload, se é um objeto, se é uma coleção, se é um inteiro.
`getLocality(payload)` tem necessidade de criar uma função para extrair a informação do payload da resposta? Pode ser que o payload seja complexo.
`const { locality } = response` eu sei que esse response contem UM objeto de localidade (nome no singular.
`const { localities } = response` eu sei que essa response contêm uma coleção de localidades (nome em plural).
tendo `payload` força ao dev quando olhar o código a ir conferir o que é a payload desta resposta, porque não tem outro jeito dele deduzir isso, e isso ajuda a esconder bug.
PS.: Meu objetivo não é fazer code review da parada, mas abordar esse padrão parece trazer complexidade ao problema em troca de ter certeza que eu posso dar `const { payload } = response;`

4. Resposta é em JSON
Não perder o foco que a resposta da API é em JSON, por JS ter acesso parecido com JSON tendemos a confundir.

Alguma ideia sobre a pergunta 4? `Usar path param ao invés de query param`

**Comment by hebertporto** [comment]
O que eu tenho em mente é, o que dita o retorno do `payload` é a requisição que é feita. 
../posts/  um array 
../post/:id um objeto 

não tenho objeção em modificar o tipo do retorno, porém acho complicado tirar o padrão do que se esperar.  Que é, os dados vem dentro do `payload`

**Comment by eduardomoroni** [comment]
@rafaelsmag @rafaelribeiros

**Comment by rafaelsmag** [comment]
Acho que tem vantagens nas duas opções, utilizando o payload torna mais fácil pro dev desenvolver, sempre estará no payload a resposta. Utilizando o nome do retorno torna o código mais legível, o negocio é decidir o que é mais importante pra gente e adotar o padrão. 

1. Tem que ver quais são os itens que o frontend vai utilizar, e a gente retorna somente eles.

2. Acho que seria interessante alterar o _id para id.

4. Vou ver como seria para alterar, se não for muito complexo altero de uma vez pra deixar padronizado.
